webinterface/webinterface/apps/showdb/urls.py
from django.urls import path

from . import views

app_name = 'showdb'
urlpatterns = [
path('', views.index, name = 'index'),
path('orgs', views.orgs, name = 'orgs'),
path('auth', views.auth, name = 'auth'),
path('logout', views.log_out, name = 'logout'),

path('mkcb', views.mkcb, name = 'mkcb'),
path('add_mkcb_form', views.form_add_mkcb, name = 'add_mkcb_form'),
path('add_mkcb', views.add_mkcb, name = 'add_mkcb'),
path('mkcb/<decimal_number>', views.edit_mkcb_form, name = 'edit_mkcb_form'),
path('mkcb/<decimal_number>/update', views.update_mkcb, name = "update_mkcb"),
path('delete_mkcb/<decimal_number>', views.delete_mkcb, name = 'delete_mkcb'),

path('documents', views.documents, name='documents'),
path('documents/<int:pos>', views.documents, name='documents'),
path('add_document', views.document_add_form, name='add_document'),
path('edit_document/<uuid>', views.document_edit_form, name='edit_document'),
path('edit_document/<backlink>/<number>/<uuid>', views.document_edit_form, name='edit_document'),
path('delete_document/<uuid>', views.delete_file, name='delete_document'),
path('delete_document/<backlink>/<number>/<uuid>', views.delete_file, name='delete_document'),
path('upload_file', views.upload_file, name='upload_file'),
path('upload_file/<number>', views.upload_file, name='upload_file'),
path('upload_file/<number>/<backlink>', views.upload_file, name='upload_file'),
path('update_file/<uuid>', views.update_file, name='update_file'),
path('update_file/<backlink>/<number>/<uuid>', views.update_file, name='update_file'),
path('bond_file/<number>/<backlink>', views.bond_file, name='bond_file'),
path('unbound_file/<backlink>/<number>/<uuid>', views.unbound_file, name='unbound_file'),
path('ajax_filter_files', views.ajax_filter_files, name="ajax_filter_files"),
path('ajax_filter_files/<val>', views.ajax_filter_files, name="ajax_filter_files"),

path('stations', views.stations, name = 'stations'),
path('add_station_form', views.form_add_station, name = 'add_station_form'),
# path('add_station', views.add_station, name = 'add_station'),
path('station/<number>', views.edit_station_form, name = 'edit_station_form'),
path('station/<number>/update', views.update_station, name = "update_station"),
path('delete_station/<number>', views.delete_station, name = 'delete_station'),

path('devices', views.devices, name = 'devices'),
path('devices/<int:pos>', views.devices, name = 'devices'),
path('add_device_form', views.form_add_device, name = 'add_device_form'),
path('add_device_form/<int:number>', views.form_add_device, name = 'add_device_form'),
path('add_device', views.add_device, name = 'add_device'),
path('device/<number>', views.edit_device_form, name = 'edit_device_form'),
path('device/<number>/update', views.update_device, name = "update_device"),
path('delete_device/<int:number>', views.delete_device, name = 'delete_device'),




# path('<int:botool_id>/', views.detail, name='detail'),
# path('<int:botool_id>/leave_comment', views.leave_comment, name='leave_comment')
]

webinterface/webinterface/apps/tseditor/urls.py
from django.urls import path 

from . import views

app_name = 'tseditor'
urlpatterns = [
path('', views.index, name = 'index'),
path('title/<int:titleid>', views.title, name='title'),
path('title/<int:parentid>/add_title', views.add_title, name='add_title'),
path('title/<int:titleid>/update', views.update_title, name='update_title'),
path('title/<int:titleid>/delete', views.delete_title, name='delete_title'),


path('edit_document/<int:titleid>/<uuid>', views.document_edit_form, name='edit_document'),
path('upload_file/<int:titleid>', views.upload_file, name='upload_file'),
path('update_file/<int:titleid>/<uuid>', views.update_file, name='update_file'),
path('bond_file/<int:titleid>>', views.bond_file, name='bond_file'),
path('unbound_file/<int:titleid>/<uuid>', views.unbound_file, name='unbound_file'),
path('delete_file/<uuid>/<int:titleid>', views.delete_file, name='delete_file'),


# path('title/<int:parentid>/form_add_title', views.form_add_title, name='form_add_title')
# path('<int:botool_id>/', views.detail, name='detail'),
# path('<int:botool_id>/leave_comment', views.leave_comment, name='leave_comment')
]

webinterface/webinterface/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import views

urlpatterns = [
    # path('showdb/', include('showdb.urls')),
    path('', include('showdb.urls')),
    path('tseditor/', include('tseditor.urls')),
    path('admin/', admin.site.urls),
]

# from django.conf import settings
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# from webinterface import settings
# urlpatterns += patterns('',
# url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
# { 'document_root': settings.SITE_MEDIA_ROOT }),
# )

webinterface/webinterface/apps/tseditor/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Contents(models.Model):
    parent = models.OneToOneField('Titles', models.DO_NOTHING)
    content_text = models.CharField(max_length=3000)
    location = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return f"{self.parent}: {self.content_text} ({self.location})"



    class Meta:
        managed = False
        db_table = 'contents'


class Filebond(models.Model):
    bond_id = models.AutoField(primary_key=True)
    title_id = models.IntegerField()
    uuid = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.uuid}"

    class Meta:
        managed = False
        db_table = 'filebond'


class Files(models.Model):
    uuid = models.CharField(primary_key=True, max_length=64)
    namef = models.CharField(max_length=128)
    file_id = models.CharField(unique=True, max_length=128, blank=True, null=True)
    author = models.CharField(max_length=50, blank=True, null=True)
    load_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.namef}: {self.author} ({self.load_date})"

    class Meta:
        managed = False
        db_table = 'files'

    # def set_name(self, name):
    #     self.fields['namef'] = name


class Titles(models.Model):
    title_id = models.AutoField(primary_key=True)
    parent_id = models.IntegerField()
    title = models.CharField(max_length=100)
    command = models.CharField(unique=True, max_length=50, blank=True, null=True)
    title_type = models.IntegerField()

    def __str__(self):
        return f"{self.title_id}){self.title} ({self.parent_id}): {self.command} <{self.title_type}>"

    class Meta:
        managed = False
        db_table = 'titles'

webinterface/webinterface/apps/showdb/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

import json

from uuid import uuid4
from datetime import datetime

from .forms import *
from .models import Stations
from .models import Devices
from .models import Clients
from .models import Users
from .models import DecimalNumbers
from .models import Files
from .models import Filebond

import Config

# Create your views here.


def check_user_access_to_group(request, target_group="editor"):
	if not request.user.is_authenticated:
		return False
	groups = request.user.groups.all()
	for group in groups:
		if str(group) == target_group:
			return True
	return False


def index(request):
	# data = Botool.objects.all()[:10]
	# data = {'one', 'two', 'three'}
	# stations = Stations.objects.all()
	# devices = Devices.objects.all()
	# orgs = Clients.objects.all()
	form = LoginForm()
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			print(form.cleaned_data)
	return render(request, 'showdb/auth.html', {"form": form})
	

def orgs(request):
	if not request.user.is_authenticated:
		return index(request)
	print(f"Authenticated: {request.user}")
	orgs = Clients.objects.all()
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'

	return render(request, 'showdb/orgs.html', {'orgs': orgs, 'techsupport': techsupport})

def dates(request):
	if not request.user.is_authenticated:
		return index(request)
	pass




def auth(request):
	print("Request:")
	username = request.POST["login"]
	password = request.POST["password"]
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		orgs = Clients.objects.all()
		return HttpResponseRedirect( reverse('showdb:orgs'))
		# return render(request, 'showdb/orgs.html', {'orgs': orgs})
	else:
		return HttpResponseRedirect( reverse('showdb:index'))
		# return render(request, 'showdb/auth.html')

def log_out(request):
	logout(request)
	return HttpResponseRedirect( reverse('showdb:index'))
	# return render(request, 'showdb/auth.html')





def redirect_back(request, backlink="", number=""):
	if backlink == 'docs':
		return documents(request)
	elif backlink == 'device':
		return edit_device_form(request, number)
	elif backlink == 'mkcb':
		return edit_mkcb_form(request, number)
	elif backlink == 'station':
		return edit_station_form(request, number)
	return index(request)


def document_add_form(request, text=""):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
	return render(request, 'showdb/add_document_form.html', {'form': form, 'text': text})


def document_edit_form(request, uuid, backlink="docs", number="0"):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
			for i in form.cleaned_data:
				print(i)
	form.for_update(uuid)
	# if backlink:
	# 	return redirect_back(request, backlink, number)
	return render(request, 'showdb/add_document_form.html', {'form': form, 'backlink': backlink, 'number':number, 'uuid': uuid})

def documents(request, pos=0):
	step = 1000
	if not request.user.is_authenticated:
		return index(request)
	files = Files.objects.all()[pos*step:(pos+1)*step]
	count_files = Files.objects.count()
	if pos < 0:
		pos = 0
	if pos > count_files:
		pos = count_files
	pages = []
	k = 0
	while k * step < count_files:
		pages.append(k)
		k += 1
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'
	return render(request, 'showdb/documents.html', {'techsupport':techsupport, 'files': files, 'pos':pos, 'pages': pages, 'count_files':count_files})

def save_uploaded_file(request, number = ""):
	if not request.user.is_authenticated:
		return index(request)
	print(f"save file.")
	location = Config.files_location
	uuid = uuid4()
	date = datetime.now().strftime("%Y-%m-%d")
	user_name = request.user.username
	frequest = request.FILES["file"]
	with open(f"{location}/{uuid}", "wb+") as destination:
		for chunk in frequest.chunks():
			destination.write(chunk)
	try:
		print(request.POST)
		file_name = request.POST['file_name']
		if not file_name:
			file_name = frequest
		file_obj = Files.objects.create(uuid=uuid, typef=request.POST['file_type'], namef=file_name, file_id=None, author=user_name, load_date=date)
		file_obj.save()
		if number:
			bond = Filebond.objects.create(snumber=number, uuid=uuid)
			bond.save()
	except Exception as e:
		print(e)

def upload_file(request, number="", backlink=""):
	print(f"upload_file({number}, {backlink})")
	if not request.user.is_authenticated:
		return index(request)
	if request.method == "POST":
		file_form = AddDocument(request.POST, request.FILES)
		if file_form.is_valid():
			save_uploaded_file(request, number)
	else:
		file_form = AddDocument()
	if backlink:
		return redirect_back(request, backlink, number)
	return render(request, 'showdb/add_document_form.html', {'form': file_form, 'number': number})

def update_file(request, uuid="", backlink="", number=""):
	print(f"UPDATE_FILE({uuid})")
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
		# else:
		# 	print(form.non_field_errors)
		# 	for field in form.cleaned_data:
		# 		print(field)
		# 		print(form.cleaned_data[field])
		file_type = form.cleaned_data['file_type']
		file_name = form.cleaned_data['file_name']
		file = Files.objects.get(uuid=uuid)
		if file_type:
			file.file_type = file_type
		if file_name:
			file.namef = file_name
		file.save()
	else:
		print("NOT")
	form.for_update(uuid)
	if backlink:
		return redirect_back(request, backlink, number)
	return render(request, 'showdb/edit_document_form.html', {'form': form})


def bond_file(request, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	form = SelectFileForm()
	if request.method == 'POST':
		form = SelectFileForm(request.POST)
		if form.is_valid():
			print(f"uuid: {form.cleaned_data['file']}")
			files = Filebond.objects.filter(snumber=number, uuid=form.cleaned_data['file'])
			print(f"Files: {files}")
			print(len(files))
			if len(files) == 0:
				fb = Filebond.objects.create(snumber=number, uuid=form.cleaned_data['file'])
				fb.save()
	if backlink:
		return redirect_back(request, backlink, number)
	return index(request)

def unbound_file(request, uuid, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	print("Unbond file")
	Filebond.objects.filter(snumber=number, uuid=uuid).delete()
	return redirect_back(request, backlink, number)




def delete_file(request, uuid, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	Files.objects.filter(uuid=uuid).delete()
	Filebond.objects.filter(uuid=uuid).delete()
	if backlink:
		return redirect_back(request, backlink, number)
	return HttpResponseRedirect( reverse('showdb:documents'))


def ajax_post_parser(request):
	pass

def ajax_filter_files(request):
	if not request.user.is_authenticated:
		return index(request)
	if request.method == 'POST':
		filter_text = request.POST.get('text')
		# filter_name = request.POST.get('name')
		# filter_type = request.POST.get('type')
		# filter_date = request.POST.get('date')
		files = {}
		if filter_text:
			if len(filter_text) < 4:
				filess = Files.objects.filter(typef=filter_text.lower())
			elif '-' in filter_text:
				filess = Files.objects.filter(load_date=filter_text)
			else:
				filess = Files.objects.filter(namef=filter_text) 
			print(f"Count: {filess.count()}")
			return HttpResponse(filess)
		return HttpResponse(json.dumps({'text': f"Another {filter_text}", 'files':files}), content_type="application/json")
	else :
		print("Stay out")
		return render_to_response('index.html', locals())







def mkcb(request):
	if not request.user.is_authenticated:
		return index(request)
	mkcb = DecimalNumbers.objects.all()
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'
	return render(request, 'showdb/mkcb.html', {'mkcb': mkcb, 'techsupport': techsupport})


def form_add_mkcb(request, text=""):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDecimalNumber()
	if request.method == 'POST':
		form = AddDecimalNumber(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
	return render(request, 'showdb/add_mkcb_form.html', {'form': form, 'text': text})

def edit_mkcb_form(request, decimal_number):
	print(f"edit_mkcb_form({decimal_number})")
	if not request.user.is_authenticated:
		return index(request)
	number = DecimalNumbers.objects.get(mkcb = decimal_number)
	bonds = Filebond.objects.filter(snumber=decimal_number)
	files = []
	print(f"Filebonds: \r\n{bonds}")
	for bond in bonds:
		file = Files.objects.get(uuid = bond)
		files.append(file)
		print(f"file: {file}")
	file_form = AddDocument()
	select_form = SelectFileForm()
	mkcb_form = EditDecimalNumber()
	mkcb_form.set_name(number.field_name)
	return render(request, 'showdb/edit_mkcb_form.html', {'mkcb_form': mkcb_form, 'file_form': file_form, 'select_form': select_form, 'decimal_obj': number, 'files':files})

def add_mkcb(request):
	if not request.user.is_authenticated:
		return index(request)
	print(f"add_mkcb()")
	try:
		number = request.POST['number']
		dot = number.find('.')
		dash = number.find('-')
		print(number)

		if dot == 6 and (len(number) == 10 and dash == -1 or len(number) == 13 and dash == 10):

webinterface/webinterface/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<link rel="shortcut icon" href="{% static 'gfm.png' %}" type="image/png">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Base{% endblock %}</title>
	{% block common_style %}
		<style type="text/css">
			html, body {
		      min-height: 100%;
		      }
		      /*body, div, form, input, select { 
		      padding: 0;
		      margin: 0;
		      outline: none;
		      font-family: Roboto, Arial, sans-serif;
		      font-size: 14px;
		      color: #666;
		      line-height: 22px;
		      }*/
			.file-table {
			   border: 0px solid black;
			   border-radius: 4px;
			   background: darkblue;
			
			& th {
			   border: 0px solid darkblue;
			   color: darkblue;
			   border-radius: 1px;
			   padding: 8px;
			   background: lightblue;
			}
			/* границы ячеек тела таблицы */
			
			& td {
				background: lightblue;
			   border: 0px solid darkblue;
			   border-radius: 1px;
			   padding-left: 8px;
			   padding-right: 8px;
			   color: darkblue;
			}
		}

			.btn {
				border:1px solid darkblue;
				border-radius: 4px;
				background: #ccf;
				color: darkblue;
				padding: 2px;
				text-decoration: none;
			}

			.btn:hover {
				background: white;
			}


			.logout {
				border: 0px;
        text-decoration: none;
        background: #f9f9f9;
        color: #8f8f8f;
        font-size: 26px;
        font-weight: 400;
        transition: all 0.5s ease-in-out;
/*        transition-property: width;*/
        position: relative;
        text-transform: uppercase;
        margin-top: 35px;
        margin-right: 35px;
        padding: 2px;

        &::before {
          content: attr(data-item);
          transition: 0.5s;
          color: #1818af;
          position: absolute;
          top: 0;
          bottom: 0;
          left: 0;
          right: 0;
          width: 0;
          overflow: hidden;
        }

        &:hover {
          &::before {
            width: 100%;
            transition: all 0.5s ease-in-out;
            color: #11c;
          }
        }
      }

			/*button {
				border:1px solid darkblue;
				border-radius: 4px;
				background: #ccf;
				color: black;
				padding: 4px;
				text-decoration: none;
			}

			button:hover {
				background: white;
			}*/

			a:hover {
				color: darkblue;
/*				font-weight: bold;*/
			}

			.form-error {
				color: red;
			}

			#menu_block {
/*				margin-top: 30px;*/
				padding: 10px;
/*				background: #6868ff;*/
/*				border-radius: 6px;*/
			}


      .menu {
      	padding: 5px;
      	text-decoration: none;
      	font-size: 28px;
      }


			.menus {
				font-size: 28px;
/*				color: black;*/
				text-decoration: none;
				background: #ccf;
				padding: 8px;
				margin-left: 3px;
				border-radius: 0px;
				border: 1px solid #ccf;
			}

			.menus:hover {
				font-size: 28px;
				color: darkblue;
				font-weight: normal;
/*				padding: 15px;*/
				border: 1px solid darkblue;
			}

			.filters {
				float: right;
				border: 2px solid #ddd;
				border-radius: 5px;
				padding: 8px;
			}

			#logout_block {
				float: right;
			}

			.content {
				float: left;
			}
			.cell {
				background: #eeeeff;
				border: 2px solid #00f;
				border-radius: 8px;
				padding: 7px;
				font-weight: calc(50%);
				margin-left: 5px;
				margin-bottom: 8px;
			}

			/*form {
				width: 100%;
				padding: 20px;
				background: #fff;
				box-shadow: 0 2px 5px #ccc; 
			}*/

			/*input.filter {
				width: calc(100% - 10px);
				padding: 5px;
				border: 1px solid #ccc;
				border-radius: 3px;
				vertical-align: middle;
			}

			input.filter:hover, textarea.filter:hover, select.filter:hover {
				outline: none;
				border: 1px solid #095484;
				background: #e6eef7;
			}

			option.filter {
				background: #fff;
			}

			select.filter {
				padding: 7px 0;
				border-radius: 3px;
				border: 1px solid #ccc;
				background: transparent;
			}*/



		</style>
		<style>
      /*html, body {
      min-height: 100%;
      }
      body, div, form, input, select { 
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 14px;
      color: #666;
      line-height: 22px;
      }*/

      /*.filters {
      display: flex;
      float: right;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 3px;
      }
      .filters {
      width: 100%;
      padding: 20px;
      background: #fff;
      box-shadow: 0 2px 5px #ccc; 
      }*/
      input {
      width: calc(100% - 10px);
      padding: 5px;
      border: 1px solid #ccc;
      border-radius: 3px;
      vertical-align: middle;
      }
      input:hover, textarea:hover, select:hover {
      outline: none;
      border: 1px solid #095484;
      background: #e6eef7;
      }

      select {
      padding: 7px 0;
      border-radius: 3px;
      border: 1px solid #ccc;
      background: transparent;
      }
      select {
      width: 100%;
      }

      select, input {
      	margin-bottom: 10px;
      }
      option {
      background: #f8f8ff;
      border-radius: 8px;
      }

      .btn-block {
      margin-top: 20px;
      text-align: center;
      }


      .filter-btn {
      width: 150px;
      padding: 10px;
      border: none;
      -webkit-border-radius: 5px; 
      -moz-border-radius: 5px; 
      border-radius: 5px; 
      background-color: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }

      .filter-btn:hover{
      background-color: #0666a3;
      font-size: 16px;
      color: #fff;}



/*      FORMS*/

		.main-div-form {
      display: flex;
      float: left;
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 3px;
      border: 1px solid #ccc;
      box-shadow: 0 2px 5px #ccc; 
      margin-top: 10px;
      margin-left: 10px;
      margin-bottom: 110px;
      padding: 8px;
      }

      .div-form {
      justify-content: center;
      align-items: center;
      height: inherit;
      padding: 3px;
      border: 1px solid #ccc;
      box-shadow: 0 2px 5px #ccc; 
      margin-top: 10px;
      margin-left: 10px;
      padding: 8px;
      }
		
		.backbutton {
      text-decoration: none;
/*      	font-weight: bold;*/
      }

      .backbutton {
      width: 150px;
      padding: 10px;
      border: none;
      -webkit-border-radius: 5px; 
      -moz-border-radius: 5px; 
      border-radius: 5px; 
      background-color: #095484;
      font-size: 16px;
      color: #fff;
      cursor: pointer;
      }

      .backbutton:hover {
      background-color: #0666a3;
      font-size: 16px;
      color: #fff;
  }

  .btn-block {
      margin-top: 20px;
      text-align: center;
      }

      .back {
      	margin-top: 20px;
      	margin-left: 20px;
      }

  .pages, .current-page {
  	font-size: 20px;
  }




nav {
  margin: 5px;
  background: #f9f9f9;
  padding: 5px;
  .menuItems {
    list-style: none;
    display: flex;

    .menu-li {
      margin: 16px;

      .menu-a {
        text-decoration: none;
        color: #8f8f8f;
        font-size: 26px;
        font-weight: 400;
        transition: all 0.5s ease-in-out;
/*        transition-property: width;*/
        position: relative;
        text-transform: uppercase;

        &::before {
          content: attr(data-item);
          transition: 0.5s;
          color: #1818af;
          position: absolute;
          top: 0;
          bottom: 0;
          left: 0;
          right: 0;
          width: 0;
          overflow: hidden;
        }

        &:hover {
          &::before {
            width: 100%;
            transition: all 0.5s ease-in-out;
          }
        }
      }
    }
  }
}

	.device-block {
		border: 1px solid #ccc;
		border-radius: 1px;
		padding: 8px;
		margin-top: 4px;
		margin-left: 8px;
		min-width: 200px;
		max-width: 600px;
/*		box-shadow: 0 2px 5px #ccc;*/
	}

	.subtitle-block {
		border: 1px solid #ccc;
		border-radius: 5px;
		padding: 8px;
		margin-top: 4px;
		margin-left: 8px;
		min-width: 200px;
		max-width: 600px;
/*		box-shadow: 0 2px 5px #ccc;*/
	}

</style>
	{% endblock %}
	{% block style %}
	{% endblock %}

	<script src= 
        "https://code.jquery.com/jquery-3.6.0.min.js"
        integrity= 
"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" 
        crossorigin="anonymous"> 
    </script> 
</head>
	<body>
		<div>
			{% block menu %}
				<div id="logout_block">
					<form action="{% url 'showdb:logout' %}" method="POST">
						{% csrf_token %}
						<button class="logout" type="submit" data-item="Выйти">Выйти</button>
					</form>
				</div>
					<nav>
						<ul class="menuItems">
							<li class="menu-li"><a class="menu-a" href="{% url 'showdb:orgs' %}" data-item="Организации">Организации</a></li>
							<!-- <li><a class="menu" href="">Даты </a></li> -->
							<li class="menu-li"><a class="menu-a" href="{% url 'showdb:mkcb' %}"data-item="МКЦБ">МКЦБ</a></li>
							<li class="menu-li"><a class="menu-a" href="{% url 'showdb:stations' %}"data-item="Станции">Станции</a></li>
							<li class="menu-li"><a class="menu-a" href="{% url 'showdb:devices' %}"data-item="Датчики">Датчики</a></li>
							<li class="menu-li"><a class="menu-a" href="{% url 'showdb:documents' %}"data-item="Документы">Документы</a></li>
							{% if techsupport %}
							<li class="menu-li"><a class="menu-a" href="{% url 'tseditor:index' %}"data-item="{{techsupport}}">{{techsupport}}</a></li>
							{% endif %}
						</ul>
					</nav>
					<hr>
			{% endblock %}
		</div>
		<div>
			<br>
			<br>

			{% block content %}Empty.{% endblock %}
		</div>
	</body>
</html>