webinterface/webinterface/apps/showdb/urls.py
from django.urls import path

from . import views

app_name = 'showdb'
urlpatterns = [
path('', views.index, name = 'index'),
path('orgs', views.orgs, name = 'orgs'),
path('auth', views.auth, name = 'auth'),
path('logout', views.log_out, name = 'logout'),

path('mkcb', views.mkcb, name = 'mkcb'),
path('add_mkcb_form', views.form_add_mkcb, name = 'add_mkcb_form'),
path('add_mkcb', views.add_mkcb, name = 'add_mkcb'),
path('mkcb/<decimal_number>', views.edit_mkcb_form, name = 'edit_mkcb_form'),
path('mkcb/<decimal_number>/update', views.update_mkcb, name = "update_mkcb"),
path('delete_mkcb/<decimal_number>', views.delete_mkcb, name = 'delete_mkcb'),

path('documents', views.documents, name='documents'),
path('documents/<int:pos>', views.documents, name='documents'),
path('add_document', views.document_add_form, name='add_document'),
path('edit_document/<uuid>', views.document_edit_form, name='edit_document'),
path('edit_document/<backlink>/<number>/<uuid>', views.document_edit_form, name='edit_document'),
path('delete_document/<uuid>', views.delete_file, name='delete_document'),
path('delete_document/<backlink>/<number>/<uuid>', views.delete_file, name='delete_document'),
path('upload_file', views.upload_file, name='upload_file'),
path('upload_file/<number>', views.upload_file, name='upload_file'),
path('upload_file/<number>/<backlink>', views.upload_file, name='upload_file'),
path('update_file/<uuid>', views.update_file, name='update_file'),
path('update_file/<backlink>/<number>/<uuid>', views.update_file, name='update_file'),
path('bond_file/<number>/<backlink>', views.bond_file, name='bond_file'),
path('unbound_file/<backlink>/<number>/<uuid>', views.unbound_file, name='unbound_file'),
path('ajax_filter_files', views.ajax_filter_files, name="ajax_filter_files"),
path('ajax_filter_files/<val>', views.ajax_filter_files, name="ajax_filter_files"),

path('stations', views.stations, name = 'stations'),
path('add_station_form', views.form_add_station, name = 'add_station_form'),
# path('add_station', views.add_station, name = 'add_station'),
path('station/<number>', views.edit_station_form, name = 'edit_station_form'),
path('station/<number>/update', views.update_station, name = "update_station"),
path('delete_station/<number>', views.delete_station, name = 'delete_station'),

path('devices', views.devices, name = 'devices'),
path('devices/<int:pos>', views.devices, name = 'devices'),
path('add_device_form', views.form_add_device, name = 'add_device_form'),
path('add_device_form/<int:number>', views.form_add_device, name = 'add_device_form'),
path('add_device', views.add_device, name = 'add_device'),
path('device/<number>', views.edit_device_form, name = 'edit_device_form'),
path('device/<number>/update', views.update_device, name = "update_device"),
path('delete_device/<int:number>', views.delete_device, name = 'delete_device'),




# path('<int:botool_id>/', views.detail, name='detail'),
# path('<int:botool_id>/leave_comment', views.leave_comment, name='leave_comment')
]

webinterface/webinterface/apps/tseditor/urls.py
from django.urls import path 

from . import views

app_name = 'tseditor'
urlpatterns = [
path('', views.index, name = 'index'),
path('title/<int:titleid>', views.title, name='title'),
path('title/<int:parentid>/add_title', views.add_title, name='add_title'),
path('title/<int:titleid>/update', views.update_title, name='update_title'),
path('title/<int:titleid>/delete', views.delete_title, name='delete_title'),


path('edit_document/<int:titleid>/<uuid>', views.document_edit_form, name='edit_document'),
path('upload_file/<int:titleid>', views.upload_file, name='upload_file'),
path('update_file/<int:titleid>/<uuid>', views.update_file, name='update_file'),
path('bond_file/<int:titleid>>', views.bond_file, name='bond_file'),
path('unbound_file/<int:titleid>/<uuid>', views.unbound_file, name='unbound_file'),
path('delete_file/<uuid>/<int:titleid>', views.delete_file, name='delete_file'),


# path('title/<int:parentid>/form_add_title', views.form_add_title, name='form_add_title')
# path('<int:botool_id>/', views.detail, name='detail'),
# path('<int:botool_id>/leave_comment', views.leave_comment, name='leave_comment')
]

webinterface/webinterface/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import views

urlpatterns = [
    # path('showdb/', include('showdb.urls')),
    path('', include('showdb.urls')),
    path('tseditor/', include('tseditor.urls')),
    path('admin/', admin.site.urls),
]

# from django.conf import settings
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# from webinterface import settings
# urlpatterns += patterns('',
# url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
# { 'document_root': settings.SITE_MEDIA_ROOT }),
# )

webinterface/webinterface/apps/tseditor/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Contents(models.Model):
    parent = models.OneToOneField('Titles', models.DO_NOTHING)
    content_text = models.CharField(max_length=3000)
    location = models.CharField(max_length=255, blank=True, null=True)


    def __str__(self):
        return f"{self.parent}: {self.content_text} ({self.location})"



    class Meta:
        managed = False
        db_table = 'contents'


class Filebond(models.Model):
    bond_id = models.AutoField(primary_key=True)
    title_id = models.IntegerField()
    uuid = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.uuid}"

    class Meta:
        managed = False
        db_table = 'filebond'


class Files(models.Model):
    uuid = models.CharField(primary_key=True, max_length=64)
    namef = models.CharField(max_length=128)
    file_id = models.CharField(unique=True, max_length=128, blank=True, null=True)
    author = models.CharField(max_length=50, blank=True, null=True)
    load_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.namef}: {self.author} ({self.load_date})"

    class Meta:
        managed = False
        db_table = 'files'

    # def set_name(self, name):
    #     self.fields['namef'] = name


class Titles(models.Model):
    title_id = models.AutoField(primary_key=True)
    parent_id = models.IntegerField()
    title = models.CharField(max_length=100)
    command = models.CharField(unique=True, max_length=50, blank=True, null=True)
    title_type = models.IntegerField()

    def __str__(self):
        return f"{self.title_id}){self.title} ({self.parent_id}): {self.command} <{self.title_type}>"

    class Meta:
        managed = False
        db_table = 'titles'

webinterface/webinterface/apps/showdb/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

import json

from uuid import uuid4
from datetime import datetime

from .forms import *
from .models import Stations
from .models import Devices
from .models import Clients
from .models import Users
from .models import DecimalNumbers
from .models import Files
from .models import Filebond

import Config

# Create your views here.


def check_user_access_to_group(request, target_group="editor"):
	if not request.user.is_authenticated:
		return False
	groups = request.user.groups.all()
	for group in groups:
		if str(group) == target_group:
			return True
	return False


def index(request):
	# data = Botool.objects.all()[:10]
	# data = {'one', 'two', 'three'}
	# stations = Stations.objects.all()
	# devices = Devices.objects.all()
	# orgs = Clients.objects.all()
	form = LoginForm()
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			print(form.cleaned_data)
	return render(request, 'showdb/auth.html', {"form": form})
	

def orgs(request):
	if not request.user.is_authenticated:
		return index(request)
	print(f"Authenticated: {request.user}")
	orgs = Clients.objects.all()
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'

	return render(request, 'showdb/orgs.html', {'orgs': orgs, 'techsupport': techsupport})

def dates(request):
	if not request.user.is_authenticated:
		return index(request)
	pass




def auth(request):
	print("Request:")
	username = request.POST["login"]
	password = request.POST["password"]
	user = authenticate(request, username=username, password=password)
	if user is not None:
		login(request, user)
		orgs = Clients.objects.all()
		return HttpResponseRedirect( reverse('showdb:orgs'))
		# return render(request, 'showdb/orgs.html', {'orgs': orgs})
	else:
		return HttpResponseRedirect( reverse('showdb:index'))
		# return render(request, 'showdb/auth.html')

def log_out(request):
	logout(request)
	return HttpResponseRedirect( reverse('showdb:index'))
	# return render(request, 'showdb/auth.html')





def redirect_back(request, backlink="", number=""):
	if backlink == 'docs':
		return documents(request)
	elif backlink == 'device':
		return edit_device_form(request, number)
	elif backlink == 'mkcb':
		return edit_mkcb_form(request, number)
	elif backlink == 'station':
		return edit_station_form(request, number)
	return index(request)


def document_add_form(request, text=""):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
	return render(request, 'showdb/add_document_form.html', {'form': form, 'text': text})


def document_edit_form(request, uuid, backlink="docs", number="0"):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
			for i in form.cleaned_data:
				print(i)
	form.for_update(uuid)
	# if backlink:
	# 	return redirect_back(request, backlink, number)
	return render(request, 'showdb/add_document_form.html', {'form': form, 'backlink': backlink, 'number':number, 'uuid': uuid})

def documents(request, pos=0):
	step = 1000
	if not request.user.is_authenticated:
		return index(request)
	files = Files.objects.all()[pos*step:(pos+1)*step]
	count_files = Files.objects.count()
	if pos < 0:
		pos = 0
	if pos > count_files:
		pos = count_files
	pages = []
	k = 0
	while k * step < count_files:
		pages.append(k)
		k += 1
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'
	return render(request, 'showdb/documents.html', {'techsupport':techsupport, 'files': files, 'pos':pos, 'pages': pages, 'count_files':count_files})

def save_uploaded_file(request, number = ""):
	if not request.user.is_authenticated:
		return index(request)
	print(f"save file.")
	location = Config.files_location
	uuid = uuid4()
	date = datetime.now().strftime("%Y-%m-%d")
	user_name = request.user.username
	frequest = request.FILES["file"]
	with open(f"{location}/{uuid}", "wb+") as destination:
		for chunk in frequest.chunks():
			destination.write(chunk)
	try:
		print(request.POST)
		file_name = request.POST['file_name']
		if not file_name:
			file_name = frequest
		file_obj = Files.objects.create(uuid=uuid, typef=request.POST['file_type'], namef=file_name, file_id=None, author=user_name, load_date=date)
		file_obj.save()
		if number:
			bond = Filebond.objects.create(snumber=number, uuid=uuid)
			bond.save()
	except Exception as e:
		print(e)

def upload_file(request, number="", backlink=""):
	print(f"upload_file({number}, {backlink})")
	if not request.user.is_authenticated:
		return index(request)
	if request.method == "POST":
		file_form = AddDocument(request.POST, request.FILES)
		if file_form.is_valid():
			save_uploaded_file(request, number)
	else:
		file_form = AddDocument()
	if backlink:
		return redirect_back(request, backlink, number)
	return render(request, 'showdb/add_document_form.html', {'form': file_form, 'number': number})

def update_file(request, uuid="", backlink="", number=""):
	print(f"UPDATE_FILE({uuid})")
	if not request.user.is_authenticated:
		return index(request)
	form = AddDocument()
	if request.method == 'POST':
		form = AddDocument(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
		# else:
		# 	print(form.non_field_errors)
		# 	for field in form.cleaned_data:
		# 		print(field)
		# 		print(form.cleaned_data[field])
		file_type = form.cleaned_data['file_type']
		file_name = form.cleaned_data['file_name']
		file = Files.objects.get(uuid=uuid)
		if file_type:
			file.file_type = file_type
		if file_name:
			file.namef = file_name
		file.save()
	else:
		print("NOT")
	form.for_update(uuid)
	if backlink:
		return redirect_back(request, backlink, number)
	return render(request, 'showdb/edit_document_form.html', {'form': form})


def bond_file(request, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	form = SelectFileForm()
	if request.method == 'POST':
		form = SelectFileForm(request.POST)
		if form.is_valid():
			print(f"uuid: {form.cleaned_data['file']}")
			files = Filebond.objects.filter(snumber=number, uuid=form.cleaned_data['file'])
			print(f"Files: {files}")
			print(len(files))
			if len(files) == 0:
				fb = Filebond.objects.create(snumber=number, uuid=form.cleaned_data['file'])
				fb.save()
	if backlink:
		return redirect_back(request, backlink, number)
	return index(request)

def unbound_file(request, uuid, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	print("Unbond file")
	Filebond.objects.filter(snumber=number, uuid=uuid).delete()
	return redirect_back(request, backlink, number)




def delete_file(request, uuid, backlink="", number=""):
	if not request.user.is_authenticated:
		return index(request)
	Files.objects.filter(uuid=uuid).delete()
	Filebond.objects.filter(uuid=uuid).delete()
	if backlink:
		return redirect_back(request, backlink, number)
	return HttpResponseRedirect( reverse('showdb:documents'))


def ajax_post_parser(request):
	pass

def ajax_filter_files(request):
	if not request.user.is_authenticated:
		return index(request)
	if request.method == 'POST':
		filter_text = request.POST.get('text')
		# filter_name = request.POST.get('name')
		# filter_type = request.POST.get('type')
		# filter_date = request.POST.get('date')
		files = {}
		if filter_text:
			if len(filter_text) < 4:
				filess = Files.objects.filter(typef=filter_text.lower())
			elif '-' in filter_text:
				filess = Files.objects.filter(load_date=filter_text)
			else:
				filess = Files.objects.filter(namef=filter_text) 
			print(f"Count: {filess.count()}")
			return HttpResponse(filess)
		return HttpResponse(json.dumps({'text': f"Another {filter_text}", 'files':files}), content_type="application/json")
	else :
		print("Stay out")
		return render_to_response('index.html', locals())







def mkcb(request):
	if not request.user.is_authenticated:
		return index(request)
	mkcb = DecimalNumbers.objects.all()
	techsupport = ''
	if check_user_access_to_group(request):
		techsupport = 'techsupport'
	return render(request, 'showdb/mkcb.html', {'mkcb': mkcb, 'techsupport': techsupport})


def form_add_mkcb(request, text=""):
	if not request.user.is_authenticated:
		return index(request)
	form = AddDecimalNumber()
	if request.method == 'POST':
		form = AddDecimalNumber(request.POST)
		if form.is_valid():
			print(f"form.cleaned_data: {form.cleaned_data}")
	return render(request, 'showdb/add_mkcb_form.html', {'form': form, 'text': text})

def edit_mkcb_form(request, decimal_number):
	print(f"edit_mkcb_form({decimal_number})")
	if not request.user.is_authenticated:
		return index(request)
	number = DecimalNumbers.objects.get(mkcb = decimal_number)
	bonds = Filebond.objects.filter(snumber=decimal_number)
	files = []
	print(f"Filebonds: \r\n{bonds}")
	for bond in bonds:
		file = Files.objects.get(uuid = bond)
		files.append(file)
		print(f"file: {file}")
	file_form = AddDocument()
	select_form = SelectFileForm()
	mkcb_form = EditDecimalNumber()
	mkcb_form.set_name(number.field_name)
	return render(request, 'showdb/edit_mkcb_form.html', {'mkcb_form': mkcb_form, 'file_form': file_form, 'select_form': select_form, 'decimal_obj': number, 'files':files})

def add_mkcb(request):
	if not request.user.is_authenticated:
		return index(request)
	print(f"add_mkcb()")
	try:
		number = request.POST['number']
		dot = number.find('.')
		dash = number.find('-')
		print(number)

		if dot == 6 and (len(number) == 10 and dash == -1 or len(number) == 13 and dash == 10):

webinterface/webinterface/templates/showdb/devices.html
{% extends 'base.html' %}

{% block title %}Датчики{% endblock %}

{% block style %}
	
{% endblock %}

{% block content %}
	
	{% if filter_form %}
			<div class="filters">
				<form action="{% url 'showdb:devices' %}" method="POST">
					{% csrf_token %}
					<div class="form-error">{{ text }}</div>
						<h3>Фильтры:</h3>
						<hr>
						{% for field in filter_form %}
							<div class="filter-field">
								{{ field.label}}<br>
								{{ field }}
							</div>
						{% endfor %}
					<button class="filter-btn" type="submit">Применить</button>
				</form>
			</div>
		{% endif %}

	<h2>Датчики</h2><hr>

	<p><a class="backbutton" href="{% url 'showdb:add_device_form' %}"><b>Добавить</b></a></p>

	{% if devices %}
		<div class="content">
			<p>Количество: {{ count }}</p>
			<div>
				{% for lnk in pages %}
					{% if lnk != pos %}
					<a class="pages" href="{% url 'showdb:devices' lnk %}">{{lnk}}</a>
					{% else %}
					<a class="current-page">{{lnk}}</a>
					{% endif %}
				{% endfor %}
			</div><br>
			{% for device in devices %}
				<div class="cell">
					Заводской номер: <a href="{% url 'showdb:edit_device_form' device.serial_number %}">{{device.serial_number}}</a><br>
					<hr>
					Станция: {% if device.station_number %}<a href="{% url 'showdb:edit_station_form' device.station_number.serial_number %}">{{device.station_number.serial_number}}</a>{% else %}Без станции.{% endif %}<br>
					Название: {{device.device_name}}<br>
					<a href="{% url 'showdb:edit_mkcb_form' device.mkcb %}">{{device.mkcb}}</a><br>
					Отгружен: {{device.date_out}}, {{device.org}}<br>
				</div>
			{% endfor %}
		</div>
	{% else %}
		Нет устройств.
	{% endif %}


{% endblock %}

webinterface/webinterface/templates/showdb/edit_device_form.html
{% extends 'base.html' %}
{% block title %}Редактирование Устройства{% endblock %}


{% block menu %}
<a class="backbutton" href="{% url 'showdb:devices' %}">Датчики</a>
{% endblock %}

{% block content %}

{% if device %}
	<p>
		{{device.serial_number}}<br>
		{{device.device_name}}<br>
		{% if device.station_number %}
		Станция: <a href="{% url 'showdb:edit_station_form' device.station_number.serial_number %}"> {{device.station_number}}</a><br>
		{% else %}
		Без станции.<br>
		{% endif %}
		МКЦБ: <a href="{% url 'showdb:edit_mkcb_form' device.mkcb %}">{{device.mkcb}}</a><br>
		Отгружен: {{ device.org }}, {{ device.date_out }}<br>
		Описание: {{ device.description_field }}<br>
		<br>
		{% include 'edit_device_fields.html' with form=device_form number=device.serial_number %}<br>
		<a class="backbutton" href="{% url 'showdb:delete_device' device.serial_number %}">Удалить устройство</a>
	</p>
	<p>
		{% if files %}
			<table class="file-table">
			<tr><th>Название</th><th>Тип документа</th><th>Автор</th><th>Дата загрузки</th></tr>
			{% for file in files %}
				<tr><td>{{ file.namef }}</td><td>{{ file.typef }}</td><td>{{ file.author }}</td><td>{{ file.load_date }}</td>
					<td><a href="{% url 'showdb:edit_document' 'device' device.serial_number file.uuid %}">Редактировать</a></td>
					<td><a href="{% url 'showdb:unbound_file' 'device' device.serial_number file.uuid %}">Открепить</a></td>
					<td><a href="{% url 'showdb:delete_document' 'device' device.serial_number file.uuid %}">Удалить</a></td></tr>
			{% endfor %}
			</table>
		{% else %}
			Нет файлов для этого устройства.
		{% endif %}
	</p>

	{% include 'add_file_form.html' with file_form=file_form select_form=select_form number=device.serial_number backlink='device' %}

	<!-- <div class="main-div-form">
		<form action="{% url 'showdb:upload_file' device.serial_number %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-error">{{ file_form.non_field_errors }}</div>
			{% for field in file_form %}
				<div>
					{{ field.label}}<br>
					{{ field }}
				</div>
			{% endfor %}
			<button class="backbutton" type="submit">Добавить</button>

		</form>
	</div> -->

	<!-- <form action="{% url 'showdb:upload_file' device.serial_number %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-error">{{ file_form.non_field_errors }}</div>
		{% for f in file_form %}
			<p><label class="form-label" for={{ f.id_for_label }}>{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}
		<button type="submit">Добавить</button>
    </form> -->
{% endif %}
{% endblock %}

webinterface/webinterface/templates/showdb/edit_mkcb_form.html
{% extends 'base.html' %}
{% block title %}Редактирование МКЦБ{% endblock %}


{% block menu %}
<a class="backbutton" href="{% url 'showdb:mkcb' %}">Назад</a>
{% endblock %}

{% block content %}

{% if decimal_obj %}
	<p>
		{{decimal_obj.mkcb}}<br>
		{{decimal_obj.field_name}}<br><br>
		{% include 'edit_mkcb_name_form.html' with form=mkcb_form number=decimal_obj.mkcb %}<br>
		<a class="backbutton" href="{% url 'showdb:delete_mkcb' decimal_obj.mkcb %}">Удалить децимальный номер</a>
	</p>
	<p>
		{% if files %}
			<table class="file-table">
			<tr><th>Название</th><th>Тип документа</th><th>Автор</th><th>Дата загрузки</th></tr>
			{% for file in files %}
				<tr><td>{{ file.namef }}</td><td>{{ file.typef }}</td><td>{{ file.author }}</td><td>{{ file.load_date }}</td>
					<td><a href="{% url 'showdb:edit_document' 'mkcb' decimal_obj.mkcb file.uuid %}">Редактировать</a></td>
					<td><a href="{% url 'showdb:unbound_file' 'mkcb' decimal_obj.mkcb file.uuid %}">Открепить</a></td>
					<td><a href="{% url 'showdb:delete_document' 'mkcb' decimal_obj.mkcb file.uuid %}">Удалить</a></td>
				</tr>
			{% endfor %}
			</table>
		{% else %}
			Нет файлов для этого МКЦБ.
		{% endif %}
	</p>

	{% include 'add_file_form.html' with file_form=file_form select_form=select_form number=decimal_obj.mkcb backlink='mkcb' %}

	<!-- <div class="main-div-form">
		<form action="{% url 'showdb:upload_file' decimal_obj.mkcb %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-error">{{ file_form.non_field_errors }}</div>
			{% for field in file_form %}
				<div>
					{{ field.label}}<br>
					{{ field }}
				</div>
			{% endfor %}
			<button class="backbutton" type="submit">Добавить</button>

		</form>
	</div> -->


	<!-- <form action="{% url 'showdb:upload_file' decimal_obj.mkcb %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-error">{{ file_form.non_field_errors }}</div>
		{% for f in file_form %}
			<p><label class="form-label" for={{ f.id_for_label }}>{{f.label}}: </label>{{f}}</p>
			<div class="form-error">{{f.errors}}</div>
		{% endfor %}
		<button type="submit">Добавить</button>
    </form> -->
{% endif %}
{% endblock %}

webinterface/webinterface/templates/showdb/edit_station_form.html
{% extends 'base.html' %}
{% block title %}Редактирование Станции{% endblock %}


{% block menu %}
<a class="backbutton" href="{% url 'showdb:stations' %}">Станции</a>
{% endblock %}


{% block content %}
	{% if station %}
		<p>
			Номер: {{station.serial_number}}<br>
			МКЦБ: <a href="{% url 'showdb:edit_mkcb_form' station.mkcb %}">{{station.mkcb}}</a><br>
			Отгружен: {{ station.org }}, {{ station.date_out }}<br>
			Описание: {{ station.description_field }}<br>
			<br>
			{% include 'edit_station_fields.html' with form=station_form number=station.serial_number %}<br>
			<a class="backbutton" href="{% url 'showdb:delete_station' station.serial_number %}">Удалить станцию</a>
		</p>
		<div>
			{% if devices %}
			<div>
				Устройства:<br>
				{% for device in devices %}
					<div class="device-block"><a href="{% url 'showdb:edit_device_form' device.serial_number %}">{{ device.serial_number }}</a>: {{ device.device_name }}</div>
				{% endfor %}
			</div><br>
				
			{% endif %}

			<div>
				<a class="backbutton" href="{% url 'showdb:add_device_form' station.serial_number %}">Добавить устройство</a>
			</div><br>

			<!-- {% include 'add_device_form_template.html' with form=device_form number=station.serial_number %} -->

			{% if files %}
			<div>
				<table class="file-table">
				<tr><th>Название</th><th>Тип документа</th><th>Автор</th><th>Дата загрузки</th></tr>
				{% for file in files %}
					<tr><td>{{ file.namef }}</td><td>{{ file.typef }}</td><td>{{ file.author }}</td><td>{{ file.load_date }}</td>
					<td><a href="{% url 'showdb:edit_document' 'station' station.serial_number file.uuid %}">Редактировать</a></td>
					<td><a href="{% url 'showdb:unbound_file' 'station' station.serial_number file.uuid %}">Открепить</a></td>
					<td><a href="{% url 'showdb:delete_document' 'station' station.serial_number file.uuid %}">Удалить</a></td>
				</tr>
				{% endfor %}
				</table>
			</div>
			{% else %}
				Нет файлов для этой станции.
			{% endif %}
		</div>



		{% include 'add_file_form.html' with file_form=file_form select_form=select_form number=station.serial_number backlink='station' %}


		<!-- <div class="main-div-form">
			<form action="{% url 'showdb:upload_file' station.serial_number %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-error">{{ file_form.non_field_errors }}</div>
				{% for field in file_form %}
					<div>
						{{ field.label}}<br>
						{{ field }}
					</div>
				{% endfor %}
				<button class="backbutton" type="submit">Добавить</button>

			</form>
		</div> -->

		<!-- <form action="{% url 'showdb:upload_file' station.serial_number %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-error">{{ file_form.non_field_errors }}</div>
			{% for f in file_form %}
				<p><label class="form-label" for={{ f.id_for_label }}>{{f.label}}: </label>{{f}}</p>
				<div class="form-error">{{f.errors}}</div>
			{% endfor %}
			<button type="submit">Добавить</button>
	    </form> -->
	{% endif %}
{% endblock %}

webinterface/webinterface/templates/showdb/orgs.html
{% extends 'base.html' %}

{% block title %}Организации{% endblock %}


{% block content %}

	{% if orgs %}
		{% for org in orgs %}
			<a>{{org.org}}</a><br>
		{% endfor %}
	{% else %}
		No organisations.
	{% endif %}


{% endblock %}